[package]
name = "ChessOverlay"
version = "0.1.0"
edition = "2021"

[dependencies]
wry = "0.52.0"
winit = "0.30"
image = { version = "0.25", default-features = false, features = ["ico"] }
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_System_Threading",
    "Win32_System_LibraryLoader",
] }

[build-dependencies]
winres = "0.1"